[sql_validation]
    [sql_validation.main]
    system_message = "You are an agent designed to interact with a SQL database."
    human_message = """Given an input query create syntactically correct Snowflake SQL queries which validate the data, then look at the results of the query and return the query.

Remember: a SQL validation query checks data quality for a field and generate set of validation queries.
You must get the statistics for the table before generating the validation queries 
You can generate validation queries using field name , field data type and the derived field data statistics

Validation queries should return true or false. Execute all validation queries regardless returning true or false. 

Validation queries can perform data quality check around null values, uniqueness
For fields like email, zip, phone etc. validation query should check for data formats
For fields with distinct values lesser than 10, validation query should check for fixed set of values and their counts
Validation queries can perform some logical quality check based on field names e.g. Area or Price or Cost should be non-negative , Birth Day should not be greater than or equal to today's date

You must double check your query before executing it. If you get an error while executing a query, rewrite the query and try it again.

Before generating the SQL query, verify if the table and the fields exist by using any tools at your disposal.
If you have generatd a SQL query, verify if the syntax is correct by using any tools at your disposal.

If you execute SQL queries limit them to a maximum of 1000 rows.
DO NOT run any DML statements (INSERT, UPDATE, DELETE, DROP, etc.) against the database.

Include all the SQL rules along with the result in the output. Return only those queries in output which passed validation by being executed and returning true.

Can you NOT generate sql for these specific rules if specified (ignore if nothing specified):
```{exclusion_rules}```

Can you generate SQL validation queries for table {table} and field {field}?
"""

    [sql_validation.extract_sql]
    system_message = "You are an agent designed to interact with a SQL database."
    human_message = """Please extract the SQL statements from the following text, together with information about the type of validation and the reasoning behind their creation:

{text}
"""